MONITOR {{ OPNsense.ApcUps.general.upsName|default("BK650M2") }}@localhost 1 {{ OPNsense.ApcUps.general.monitorUser|default("monuser") }} {{ OPNsense.ApcUps.general.monitorPassword|default("apcupsbk650m2") }} master
MINSUPPLIES 1
SHUTDOWNCMD "/sbin/shutdown -p +0"
NOTIFYCMD /usr/local/sbin/upssched
POLLFREQ 5
POLLFREQALERT 5
HOSTSYNC 15
# DEADTIME must be larger than the driver's polling interval (15s) and
# pollfreq (30s) to avoid false "data stale" warnings.
DEADTIME 45
POWERDOWNFLAG /etc/killpower
RBWARNTIME 43200
NOCOMMWARNTIME 300
FINALDELAY {{ OPNsense.ApcUps.shutdown.finalDelay|default("5") }}

NOTIFYFLAG ONLINE SYSLOG+WALL+EXEC
NOTIFYFLAG ONBATT SYSLOG+WALL+EXEC
NOTIFYFLAG LOWBATT SYSLOG+WALL+EXEC
NOTIFYFLAG FSD SYSLOG+WALL+EXEC
NOTIFYFLAG COMMOK SYSLOG+WALL+EXEC
NOTIFYFLAG COMMBAD SYSLOG+WALL+EXEC
NOTIFYFLAG NOCOMM SYSLOG+WALL+EXEC
NOTIFYFLAG SHUTDOWN SYSLOG+WALL
