PLUGIN_NAME=		apcups-bk650m2
PLUGIN_VERSION=		2.1.0
PLUGIN_COMMENT=		APC BK650M2 UPS management for OPNsense
PLUGIN_DEPENDS=		nut
PLUGIN_MAINTAINER=	local@example.local

.include "../../Mk/plugins.mk"
